### ISSUE TITLE
Logout(FALSE)

### ISSUE THREAD

**Issue by tonyhk** [haseydesign/flexi-auth#10]
Hi, i found logout(FALSE) function will log out all session,
the problem is in "application/models/flexi_auth_lite_model.php"
$remember_token & $remember_series did not have any value 

so i have to manual add 

$remember_token = get_cookie($this->auth->cookie_name['remember_token']);
$remember_series = get_cookie($this->auth->cookie_name['remember_series']);

after  
if (!is_numeric($user_id))
{
    return FALSE;
}

function delete_database_login_session($user_id, $all_sessions = TRUE)

---

// Check whether to delete all sessions for user on all browers they may be logged in on, or just this session.
if (!$all_sessions && isset($remember_token))
{  
// If deleting a login session not associated to a 'Remember me' cookie.
if (!isset($remember_series))
{
$remember_series = '';
}

**Comment by haseydesign** [comment]
Good spot, this is now fixed - thanks.
