### ISSUE TITLE
Undefined property: stdClass::$session_name

### ISSUE THREAD

**Issue by reypm** [haseydesign/flexi-auth#11]
I'm trying to integrate and use Flexi Auth in my new development using CI 2.1.3 but get this error:

A PHP Error was encountered
Severity: Notice
Message: Undefined property: stdClass::$session_name
Filename: libraries/Flexi_auth_lite.php
Line Number: 172

I'm autoloading class but I never call Flexi_auth_lite because in my /config/autload.php I have this:
$autoload['libraries'] = array('database', 'session', 'flexi_auth');

What I'm doing wrong?

**Comment by haseydesign** [comment]
Unfortunately the library is not compatible with the CI autoload function as the global $this->auth = new stdClass; needs to be defined prior to loading the library.

To get around this, I personally define a Controller extension named MY_Controller with CI ‘application/core’ (See: http://ellislab.com/codeigniter/user-guide/general/core_classes.html), I then manually load the library within that one controller, which then can then be loaded by all of your other controllers - in effect acting as an autoloader.

**Comment by ChrisAelbrecht** [comment]
To avoid adding $this->auth = new stdClass; in each controller before loading the Flexi Auth library you can (as mentioned by haseydesign) extend the CI_Controller and declare $auth there and assign a new stdClass to it.

``` php
<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class MY_Controller extends CI_Controller {

    public $auth;

    public function __construct() {
        parent::__construct();
        $this->auth = new stdClass;
    }
}
```

**Comment by smoizs** [comment]
A better solution ( if required ), 
in your libraries create an empty class and call the file auth.php

``` php
<?php  (defined('BASEPATH')) OR exit('No direct script access allowed');
class Auth {}
?>
```

Next, I create a class in the /application/core - lets call is base.php

``` php
<?php (defined('BASEPATH')) OR exit('No direct script access allowed');

class Base extends CI_Controller {
    function __construct() {
        parent::__construct();

               $this->load->library('auth');
        $this->load->library('flexi_auth'); 

        if ($this->flexi_auth->is_logged_in_via_password())  {
            if (!$this->flexi_auth->is_admin()) {
                redirect('login');
            }
        } else {
            redirect('login');
        }

    }
}
```

This ensure's that the flex_auth library is loaded and all requests authenticate the user.

Now for your controller ..

``` php
class Example extends Base {

    public function __construct() {
        parent::__construct();
    }
}
```

**Comment by faouzidmx** [comment]
I use codeigniter HMVC and after implementing flexi auth, I have the following errors: 

Message: Creating default object from empty value 
Filename: models / flexi_auth_lite_model.php 

So I followed your solution by creating an empty auth class as well as creating a custom My_Controller controller, but I still have the following errors: 

Message: Creating default object from empty value 
Filename: models / flexi_auth_lite_model.php 
Message: Undefined property: Auth :: $ tbl_col_user_account 
Filename: models / flexi_auth_model.php 

Can you help me please?

**Comment by carn1x** [comment]
Getting the same error as @faouzidmx

**Comment by ranrolls** [comment]
The only way out of this error if we are using ci + hvmc + fa

is to switch on production environment for ci. in index.php at root

If anyone has any better suggestions then kindly share your idea here after testing it.
