### ISSUE TITLE
Sessions not staying active in 3.0-dev

### ISSUE THREAD

**Issue by troytc** [haseydesign/flexi-auth#18]
I'm not sure if it's too early to tell or not, but I've been testing flexi-auth with CI 3.0-dev.

Everything seems to be going smoothly, except for sessions.  I've set all the settings as described in the install instructions, but sessions only stay open for 5 minutes (specified by `$config['sess_time_to_update'] = 300;` in config) as opposed to 120 minutes (specified by `$config['sess_expiration'] = 7200;` in config).  I've changed all the calls to `$this->load->library('session');` to `$this->load->driver('session');` as specified in the [3.0-dev docs](http://ci-docs.raptblue.com/installation/upgrade_300.html#step-5-convert-your-session-usage-from-library-to-driver).

I'm using the demo files directly from the zip as well as the CI 3.0-dev files from the zip.

Any thoughts or should I just wait it out until 3.0 is released?

**Comment by haseydesign** [comment]
Sorry, but at this point in time, flexi auth has only been developed and tested on CI2.
