### ISSUE TITLE
No explanantion for using custom database tables.

### ISSUE THREAD

**Issue by manan-jadhav** [haseydesign/flexi-auth#3]
I'm currently developing badwords filter for flexi-auth, i needed custom DB table, so i went through the config file,  i could see that there is a definition of creating/defining custom tables but not on using them. 

It'd be nice of you if you could expalin me how to use my custom tables. BTW, i'm gonna sort it down asap.

And, i'm hereby declaring that i'm developing a badwords filter, that can replace OR find badwords in the given data, that could be a forum post, user name, etc. So, please, anyone else should not take the same thing other wise there will be a waste of time.

**Comment by haseydesign** [comment]
There is documentation on custom tables @ http://haseydesign.com/flexi-auth/user_guide/user_account_config#custom_user_tables

However, from your comment, you seem to suggest you are thinking of defining your badwords filter using one of these tables. This is not the intended purpose of the custom user tables, they should only be used to store data that is directly related to a specific user - name, address etc.

A feature like a badwords filter would need to be run from a standalone table that is not linked within the flexi auth library. 
As a possible method of including such a feature, before you insert a username via the flexi auth library, run a simple SQL query of the username against your badword table and check whether you have any matches. If you have no matches, then you know you can insert the username using the flexi auth library.

I hope that helps you out.

**Comment by manan-jadhav** [comment]
Thanks for this stuff, i'm thinking to better use JSON instead of SQL for this, it'll be faster and easier to maintain.
What do you think?

**Comment by haseydesign** [comment]
JSON will work just as well.
It really comes down to what you think will be easier to work with and manage.

For example, if you want to build some CRUD functionality that would allow you to insert, update or delete badwords to the existing list, then probably SQL would be better. If this isn't an issue then JSON should be just fine.

**Comment by manan-jadhav** [comment]
Yeah, i agree with you, i'd better create a new "CI Driver" for badwords filter, and then you can implement it in flexi-auth.

I think i'd go with SQL, most probably.
