### ISSUE TITLE
Custom Data Insert

### ISSUE THREAD

**Issue by dhamaso** [haseydesign/flexi-auth#9]
The library doesn't save the custom data values.
$config['database']['user_acc']['custom_columns'] = array('uacc_first_name', 'uacc_last_name'); 

User insert
$this->flexi_auth->insert_user('user@test.com', 'foo', 'bar', array('uacc_first_name' => 'Foo', 'uacc_last_name' => 'Bar'), 2, TRUE);

The custom data never insert the values for the custom columns in the user_accounts table.
![Selecci n_1s32](https://f.cloud.github.com/assets/704349/145757/4247fe86-7470-11e2-8c91-31b932480ee2.png)

**Comment by dhamaso** [comment]
Adding the lines below:
if (!empty($custom_data)) {
            foreach ($custom_data as $k => $v) {
                if(strpos($k, '.') === FALSE){ // prefix only for the primary table
                    $custom_data[$this->auth->tbl_user_account . '.' . $k] = $v;
                    unset($custom_data[$k]);
                }
            }
        }

Before : 
// Loop through custom data columns for the main user table set via config file.
foreach ($this->auth->tbl_custom_col_user_account as $column) {....

Because $this->auth->tbl_custom_col_user_account array keys are prefixed with the name of the table.
Array
(
    [user_accounts.uacc_group_fk] => 1
    [user_accounts.uacc_email] => foo@bar.com
    [user_accounts.uacc_username] => foo
    [user_accounts.uacc_password] => $2a$08$R1k5DArkilw/1yTDvnIisu8qPrNpZHytmj.Cm/iblPZsVpGkYXGie
    [user_accounts.uacc_ip_address] => 127.0.0.1
    [user_accounts.uacc_date_last_login] => 2013-02-11 12:58:56
    [user_accounts.uacc_date_added] => 2013-02-11 12:58:56
    [user_accounts.uacc_activation_token] => 51475b2c715a2a3ea8eaddfafd5f8c54cd79937f
    [user_accounts.uacc_active] => 0
    [user_accounts.uacc_suspend] => 0
    [user_accounts.uacc_salt] => VHCw56ytjK
)

So this doesn't match with the $custom_data keys.

**Comment by haseydesign** [comment]
This was broken by a previous update.
I've just pushed the fix for this problem - thanks!
